### ISSUE TITLE
Kill with with signal

### ISSUE THREAD

**Issue by glebpom** [xiaopengli89/precord#13]
Hello, and thanks for this crate.

Is it possible to kill `precord` and save the data? I want to use it in CI actions like this: 
- run `precord` in the background
- run CPU intensive task
- stop `precord` with `kill(all)` command
- collect output as artifact

**Comment by xiaopengli89** [comment]
[v0.7.12](https://github.com/xiaopengli89/precord/releases/tag/v0.7.12) should works except windows.

```py
import subprocess
import time

proc = subprocess.Popen(["precord", "-c", "sys_cpu", "-o", "foo.html"])

time.sleep(5)

proc.terminate()
proc.wait(timeout=5)
```
