### ISSUE TITLE
Can not record chrome fps in virtual machine when gpu is disabled

### ISSUE THREAD

**Issue by Alex-Sun-1875** [xiaopengli89/precord#6]
1. Open chrome, and play a video
2. Start precord to record the fps 

If not in virtual machine:
1. Open chrome with --disable-gpu command line, and play a video
2. Start precord to record the fps 

The fps still 0.

![screenshot-20220712-161224](https://user-images.githubusercontent.com/20009364/178443661-5adc9bcd-9cb7-4d2c-bc18-898229483137.png)

![screenshot-20220712-161441](https://user-images.githubusercontent.com/20009364/178443737-2e4cde98-0c90-4b9b-8e7c-c94012187066.png)

**Comment by xiaopengli89** [comment]
3bf2f68cd664e8cf635dcdece6c12b7b3fa91801 should fix the issue.

![img_v2_e7c9bc78-92a9-46ce-b725-228749ff2c3g](https://user-images.githubusercontent.com/11287532/178998724-d314808d-a772-4b09-8d96-449647c7b670.jpg)
![img_v2_ca165d76-174f-4507-874c-c62096e3750g](https://user-images.githubusercontent.com/11287532/178998710-3b503bb1-371f-4efb-bb9c-3168bdeb5325.jpg)

**Comment by Alex-Sun-1875** [comment]
nice
